// Explicit UI test fixture. Never imported by the app or deployed as a backend.
const profile = { id: "synthetic-patient", name: "Asha", email: "patient@example.test", role: "user", age: 30, bloodGroup: "O+", onboardingCompleted: true };
const doctor = { id: 1, name: "Dr. Test Mehta", specialty: "General medicine", hospital_name: "Test Care Centre", hospitalName: "Test Care Centre", consultation_fees: 500, consultationFees: 500, qualifications: "Synthetic test profile" };
const appointments: Record<string, unknown>[] = [];
const posts = [{ id: "test-post", content: "A synthetic community post for interface testing.", type: "update", author: { id: "test-author", name: "Test Community" }, createdAt: new Date().toISOString(), likeCount: 0, commentCount: 0 }];
const sessions: Record<string, unknown>[] = [];
let loggedIn = false;
const server = Bun.serve({ hostname: "127.0.0.1", port: 8093, async fetch(request) {
  const url = new URL(request.url); const path = url.pathname.replace("/api/mobile", "");
  const headers = { "Access-Control-Allow-Origin": "http://localhost:8094", "Access-Control-Allow-Headers": "Authorization, Content-Type", "Access-Control-Allow-Methods": "GET, POST, PATCH, PUT, DELETE, OPTIONS", "Access-Control-Expose-Headers": "set-auth-token" };
  const json = (data: unknown, status = 200, more = {}) => Response.json(data, { status, headers: { ...headers, ...more } });
  if (request.method === "OPTIONS") return new Response(null, { headers });
  if (path === "/auth/sign-in/email") { const body = await request.json(); if (body.email !== profile.email || body.password !== "synthetic-test-only") return json({ error: "Invalid credentials" }, 401); loggedIn = true; return json({ user: profile }, 200, { "set-auth-token": "synthetic.signed" }); }
  if (!loggedIn || request.headers.get("authorization") !== "Bearer synthetic.signed") return json({ error: "Unauthorized" }, 401);
  if (path === "/auth/get-session") return json({ user: profile, session: { expiresAt: new Date(Date.now() + 3600000).toISOString() } });
  if (path === "/auth/sign-out") { loggedIn = false; return json({ success: true }); }
  if (path === `/users/${profile.id}`) { if (request.method === "PATCH") Object.assign(profile, await request.json()); return json(profile); }
  if (path === "/doctors") return json({ data: url.searchParams.get("search") === "none" ? [] : [doctor], pagination: { totalPages: 1 } });
  if (path === "/doctors/1") return json({ data: doctor });
  if (path === "/hospitals") return json({ data: [{ id: 1, name: "Test Care Centre", city: "Test City" }] });
  if (path === "/pathlabs") return json({ data: [] });
  if (path === "/appointments") { if (request.method === "POST") { const body = await request.json(); if (!appointments.some(item => item.id === body.requestId)) appointments.push({ id: body.requestId, doctorName: doctor.name, hospitalName: doctor.hospitalName, appointmentDate: body.selectedDate, appointmentTime: body.selectedTimeSlot, appointmentMode: body.appointmentType, status: "pending_approval" }); return json({ success: true, appointment: appointments.at(-1) }); } return json({ appointments }); }
  if (path === "/community/feed") return json({ data: posts });
  if (path === "/community/posts" && request.method === "POST") { const body = await request.json(); posts.unshift({ ...posts[0], id: crypto.randomUUID(), content: body.content, author: { id: profile.id, name: profile.name } }); return json({ success: true }); }
  if (path.endsWith("/comments")) return json({ data: [] });
  if (path.endsWith("/engagement")) return json({ liked: true });
  if (path === "/ai/chat") { const body = await request.json(); return json({ response: "Synthetic response for interface testing. No medical advice is generated by this fixture.", sessionId: body.sessionId || "synthetic-chat", suggestedTitle: "Test conversation" }); }
  if (path === "/ai/sessions") { if (request.method === "POST") { const body = await request.json(); sessions.push({ ...body, id: body.sessionId }); return json({ success: true }); } return json({ sessions }); }
  if (path === "/reports" || path === "/notifications") return json({ data: [] });
  return json({ error: "Not implemented in UI fixture" }, 404);
} });
console.log(`Synthetic UI fixture: ${server.url}`);
