import { LabTests, LabTest, Support, Privacy, ServiceInfo } from "./more-screens";
import { Reports } from "./reports";
import { BlurView } from "expo-blur";
import { useEffect, useState } from "react";
import { ActivityIndicator, BackHandler, Pressable, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { AuthScreen } from "./auth-screen";
import { Care, CareDetail, Departments, SearchCare, ProviderCard } from "./care";
import { Chat } from "./chat";
import { Community } from "./community";
import { Booking, Health, AppointmentDetail, Records } from "./health";
import { Home, type Destination } from "./home";
import { Inbox } from "./inbox";
import { DeleteAccount, EditProfile, Feedback, Profile } from "./profile";
import { useSession } from "./session";
import { Button, colors, ErrorText, Glyph, ResourceState, Row, Screen, useResource, type Icon } from "./ui";
import { previewEnabled } from "./preview";
import { type CareItem } from "./api";
const tabs: { name: string; label: string; icon: Icon }[] = [{ name: "home", label: "Home", icon: "home" }, { name: "health", label: "My Health", icon: "shield-checkmark" }, { name: "chat", label: "Ask AI", icon: "sparkles-outline" }, { name: "community", label: "Community", icon: "people-outline" }, { name: "profile", label: "Profile", icon: "person-circle" }];
export function PatientApp() {
  const { session, loading, error, restore, logout, preview } = useSession();
  if (loading) return <Screen title="Viruj Health"><ActivityIndicator color={colors.primary} /></Screen>;
  if (!session && error) return <Screen title="Connection unavailable"><ErrorText message={error} /><Button title="Try again" onPress={() => void restore()} /><Button title="Sign in with another account" secondary onPress={() => void logout().catch(() => {})} /></Screen>;
  if (!session) return <View style={{ flex: 1 }}><AuthScreen />{__DEV__ && <View style={{ padding: 12, backgroundColor: colors.bg }}><Button title="Explore UI preview" secondary onPress={preview} /></View>}</View>;
  return <Workspace key={session.user.id} />;
}
function Workspace() {
  const insets = useSafeAreaInsets(); const [tab, setTab] = useState("home"); const [stack, setStack] = useState<Destination[]>([]);
  const route = stack[stack.length - 1];
  const back = () => setStack(value => value.slice(0, -1));
  const navigate = (destination: Destination) => { if (tabs.some(item => item.name === destination.name)) { setTab(destination.name); setStack([]); } else setStack(value => [...value, destination]); };
  useEffect(() => { const listener = BackHandler.addEventListener("hardwareBackPress", () => { if (stack.length) { setStack(value => value.slice(0, -1)); return true; } if (tab !== "home") { setTab("home"); return true; } return false; }); return () => listener.remove(); }, [stack.length, tab]);
  const name = route?.name || tab;
  let screen;
  if (name === "care") screen = <Care key={`${route!.kind}/${route!.query || ""}`} kind={route!.kind!} department={route!.query} navigate={navigate} back={back} />;
  else if (name === "detail") screen = <CareDetail key={`${route!.kind}/${route!.id}`} kind={route!.kind!} id={route!.id!} navigate={navigate} back={back} />;
  else if (name === "hospital-doctors") screen = <HospitalDoctors id={route!.id!} back={back} navigate={navigate} />;
  else if (name === "booking") screen = <Booking doctorId={route!.id!} back={back} complete={() => navigate({ name: "health" })} />;
  else if (name === "notifications") screen = <Inbox back={back} navigate={navigate} />;
  else if (name === "edit-profile") screen = <EditProfile back={back} />;
  else if (name === "feedback") screen = <Feedback back={back} />;
  else if (name === "delete-account") screen = <DeleteAccount back={back} />;
  else if (name === "search") screen = <SearchCare navigate={navigate} back={back} />;
  else if (name === "departments") screen = <Departments id={route?.id} navigate={navigate} back={back} />;
  else if (name === "appointment") screen = <AppointmentDetail id={route!.id!} navigate={navigate} back={back} />;
  else if (name === "records") screen = <Records navigate={navigate} back={back} />;
  else if (name === "reports") screen = <Reports back={back} />;
  else if (name === "lab-tests") screen = <LabTests navigate={navigate} back={back} />;
  else if (name === "lab-test") screen = <LabTest name={route!.query!} navigate={navigate} back={back} />;
  else if (name === "support") screen = <Support back={back} />;
  else if (name === "privacy") screen = <Privacy navigate={navigate} back={back} />;
  else if (name === "service-info") screen = <ServiceInfo name={route!.query!} navigate={navigate} back={back} />;
  else if (name === "health") screen = <Health navigate={navigate} />;
  else if (name === "chat") screen = <Chat />;
  else if (name === "community") screen = <Community />;
  else if (name === "profile") screen = <Profile navigate={navigate} />;
  else screen = <Home navigate={navigate} />;
  return <View style={{ flex: 1, backgroundColor: colors.bg }}>{screen}{!["edit-profile", "booking", "profile-setup", "onboarding", "reset-password", "auth-error", "privacy", "delete-account"].includes(name) && <BlurView intensity={70} tint="light" experimentalBlurMethod="dimezisBlurView" style={{ position: "absolute", left: 16, right: 16, bottom: Math.max(insets.bottom, 16), height: 80, borderRadius: 16, overflow: "hidden", borderWidth: 1, borderColor: "#FFFFFF80", backgroundColor: "#FFFFFF66", flexDirection: "row", alignItems: "center", paddingHorizontal: 8, boxShadow: "0 8px 32px rgba(0,0,0,0.12)" }}>{tabs.map(item => <Pressable key={item.name} accessibilityRole="tab" accessibilityLabel={item.label} accessibilityState={{ selected: tab === item.name }} onPress={() => navigate({ name: item.name })} style={{ flex: 1, minHeight: 64, alignItems: "center", justifyContent: "center" }}>{item.name === "chat" ? <View style={{ width: 56, height: 56, borderRadius: 28, backgroundColor: "#EF3038", borderWidth: 2, borderColor: "#FFFFFF55", alignItems: "center", justifyContent: "center", boxShadow: "0 4px 14px rgba(239,68,68,0.3)" }}><Text style={{ fontFamily: "Merienda", fontSize: 18, fontWeight: "700", color: "white" }}>AI</Text></View> : <><View style={{ padding: 8, borderRadius: 12, backgroundColor: tab === item.name ? "#00000012" : "transparent" }}><Glyph name={item.icon} color={tab === item.name ? "#171717" : "#4B5563"} size={20} /></View><Text style={{ fontFamily: "Merienda", marginTop: 4, fontSize: 10, color: tab === item.name ? "#171717" : "#4B5563" }}>{item.label}</Text></>}</Pressable>)}</BlurView>}</View>;
}
function HospitalDoctors({ id, back, navigate }: { id: string; back(): void; navigate(destination: Destination): void }) { const result = useResource<{ data: CareItem[] }>(`/hospitals/${id}/doctors`); return <Screen title="Hospital doctors" back={back}><ResourceState {...result} />{result.data?.data.map(item => <ProviderCard key={item.id} item={item} kind="doctors" navigate={navigate} />)}</Screen>; }
