import { useState } from "react";
import { Alert, Image, Share, View } from "react-native";
import { api, type Post, webOrigin } from "./api";
import { useSession } from "./session";
import { Body, Button, Card, Empty, ErrorText, Field, Heading, ResourceState, Screen, useResource } from "./ui";
type Comment = { id: string; content: string; author: { name: string } | null; replies?: Comment[] };
export function Community() {
  const { session } = useSession(); const [page, setPage] = useState(1);
  const feed = useResource<{ data: Post[]; pagination?: { hasMore?: boolean } }>(`/community/feed?page=${page}&limit=10`);
  const [post, setPost] = useState<Post | null>(null); const [compose, setCompose] = useState(false); const [text, setText] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function publish() { if (busy || !text.trim()) return; setBusy(true); setError(""); try { await api.request("/community/posts", { method: "POST", body: { content: text.trim(), type: "update" } }); setCompose(false); setText(""); feed.reload(); } catch (e) { setError(e instanceof Error ? e.message : "Could not post."); } finally { setBusy(false); } }
  if (post) return <PostDetail post={post} back={() => { setPost(null); feed.reload(); }} own={post.author?.id === session!.user.id} />;
  if (compose) return <Screen title="New post" back={() => setCompose(false)}><Field label="Share an update" value={text} onChangeText={setText} multiline maxLength={5000} /><Body>Posts are visible to the community.</Body><ErrorText message={error} /><Button title="Post" busy={busy} disabled={!text.trim()} onPress={() => void publish()} /></Screen>;
  return <Screen title="Community" subtitle="CONNECT"><Button title="Share an update" secondary icon="add" onPress={() => setCompose(true)} /><ResourceState {...feed} />{feed.data?.data.length === 0 && <Empty title="No posts yet" />}{feed.data?.data.map(item => <Card key={item.id}><Heading>{item.author?.name || "Community member"}</Heading><Body>{new Date(item.createdAt).toLocaleDateString()}</Body><Body>{item.content}</Body>{item.imageUrl && <Image source={{ uri: item.imageUrl }} style={{ height: 200, width: "100%", borderRadius: 14 }} />}<Button title={`${item.likeCount || 0} likes · ${item.commentCount || 0} comments`} secondary onPress={() => setPost(item)} /></Card>)}<View style={{ flexDirection: "row", gap: 10 }}>{page > 1 && <Button title="Previous" secondary onPress={() => setPage(p => p - 1)} />}{feed.data?.data.length === 10 && <Button title="Next page" secondary onPress={() => setPage(p => p + 1)} />}</View></Screen>;
}
function PostDetail({ post, back, own }: { post: Post; back(): void; own: boolean }) {
  const comments = useResource<{ data: Comment[] }>(`/community/posts/${post.id}/comments`);
  const [content, setContent] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function action(path: string, body: unknown, method = "POST") {
    if (busy) return; setBusy(true); setError(""); setNotice("");
    try { const result = await api.request<{ liked?: boolean; bookmarked?: boolean }>(`/community/posts/${post.id}${path}`, { method, body });
      if (method === "DELETE") { back(); return; }
      setNotice(path === "/report" ? "Report submitted." : path === "/bookmark" ? result.bookmarked === false ? "Bookmark removed." : "Bookmarked." : result.liked !== undefined ? result.liked ? "Liked." : "Like removed." : "Comment added.");
      if (path === "/engagement" && result.liked === undefined) { setContent(""); comments.reload(); }
    } catch (e) { setError(e instanceof Error ? e.message : "Could not update."); } finally { setBusy(false); }
  }
  return <Screen title="Post" back={back}><Card><Heading>{post.author?.name || "Community member"}</Heading><Body>{post.content}</Body>{post.imageUrl && <Image source={{ uri: post.imageUrl }} style={{ height: 220, borderRadius: 16 }} />}</Card><ErrorText message={error} />{notice && <Body>{notice}</Body>}<View style={{ flexDirection: "row", flexWrap: "wrap", gap: 8 }}><Button title="Like" secondary disabled={busy} onPress={() => void action("/engagement", { action: "like" })} /><Button title="Bookmark" secondary disabled={busy} onPress={() => void action("/bookmark", {})} /><Button title="Share" secondary onPress={() => void Share.share({ message: `${post.content}\n${webOrigin}/community` }).catch(() => setError("Could not share."))} /><Button title="Report" secondary disabled={busy} onPress={() => Alert.alert("Report post", "Choose a reason", [{ text: "Cancel", style: "cancel" }, { text: "Misinformation", onPress: () => void action("/report", { reason: "misinformation" }) }, { text: "Inappropriate", onPress: () => void action("/report", { reason: "inappropriate" }) }])} />{own && <Button title="Delete" secondary disabled={busy} onPress={() => Alert.alert("Delete post?", "This cannot be undone.", [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => void action("", undefined, "DELETE") }])} />}</View><Heading>Comments</Heading><ResourceState {...comments} />{comments.data?.data.map(comment => <Card key={comment.id}><Heading>{comment.author?.name || "Community member"}</Heading><Body>{comment.content}</Body>{comment.replies?.map(reply => <View key={reply.id} style={{ paddingLeft: 16 }}><Body>{reply.author?.name}: {reply.content}</Body></View>)}</Card>)}<Field label="Add a comment" value={content} onChangeText={setContent} multiline maxLength={2000} /><Button title="Comment" busy={busy} disabled={!content.trim()} onPress={() => void action("/engagement", { action: "comment", content: content.trim() })} /></Screen>;
}
