import { useState } from "react";
import { Image, Share, View } from "react-native";
import { api, type Post, webOrigin } from "./api";
import { useSession } from "./session";
import { Choices } from "./care";
import { pickImage } from "./media";
import { previewEnabled } from "./preview";
import { Body, Button, Card, Empty, ErrorText, Field, Heading, ResourceState, Screen, useResource, useBack } from "./ui";
type Comment = { id: string; content: string; author: { name: string } | null; replies?: Comment[] };
export function Community() {
  const { session } = useSession(); const [page, setPage] = useState(1); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("All");
  const feed = useResource<{ data: Post[]; pagination?: { hasMore?: boolean } }>(`/community/feed?page=${page}&limit=10`);
  const [post, setPost] = useState<Post | null>(null); const [compose, setCompose] = useState(false); const [text, setText] = useState(""); const [image, setImage] = useState<string>(); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function publish() { if (busy || !text.trim()) return; setBusy(true); setError(""); try { await api.request("/community/posts", { method: "POST", body: { content: text.trim(), type: "update", imageUrl: image } }); setCompose(false); setText(""); setImage(undefined); feed.reload(); } catch (e) { setError(e instanceof Error ? e.message : "Could not post."); } finally { setBusy(false); } }
  async function attach() { try { const photo = await pickImage(); if (photo) setImage(photo.dataUrl); } catch (e) { setError(e instanceof Error ? e.message : "Could not select image."); } }
  useBack(Boolean(post || compose), () => { setPost(null); setCompose(false); });
  if (post) return <PostDetail post={post} back={() => { setPost(null); feed.reload(); }} own={post.author?.id === session!.user.id} />;
  if (compose) return <Screen title="Create post" subtitle="SHARE WITH YOUR COMMUNITY" back={() => setCompose(false)}><Card><Heading>{session?.user.name}</Heading><Body>Community post · visible to everyone</Body></Card><Field label="What would you like to share?" placeholder="Share an experience or start a conversation…" value={text} onChangeText={setText} multiline maxLength={5000} /><Body>{text.length}/5000</Body><Button title={image ? "Change photo" : "Add a photo"} secondary onPress={() => void attach()} />{image && <><Image source={{ uri: image }} style={{ height: 220, borderRadius: 18 }} /><Button title="Remove photo" secondary onPress={() => setImage(undefined)} /></>}<Body>Avoid sharing someone else’s private medical information.</Body><ErrorText message={error} /><Button title={previewEnabled ? "Post in preview" : "Publish post"} busy={busy} disabled={!text.trim()} onPress={() => void publish()} /></Screen>;
  const posts = (feed.data?.data || []).filter(p => (filter !== "My posts" || p.author?.id === session?.user.id) && (filter !== "Awareness" || p.type === "awareness") && `${p.content} ${p.author?.name}`.toLowerCase().includes(query.toLowerCase()));
  return <Screen title="Community" subtitle="CONNECT & SHARE"><Card><Heading>A healthier community, together</Heading><Body>Stories, experiences and conversations from people like you.</Body><Button title="Share an update" secondary icon="add" onPress={() => setCompose(true)} /></Card><Field label="Search this page" value={query} onChangeText={setQuery} placeholder="Search posts or people" /><Choices options={["All", "My posts", "Awareness"]} value={filter} onChange={setFilter} /><ResourceState {...feed} />{!feed.loading && !feed.error && posts.length === 0 && <Empty title="No posts to show" detail="Try another filter or share your first update." />}{posts.map(item => <Card key={item.id}><Heading>{item.author?.name || "Community member"}</Heading><Body>{new Date(item.createdAt).toLocaleDateString()} · {item.type}</Body><Body>{item.content}</Body>{item.imageUrl && <Image source={{ uri: item.imageUrl }} style={{ height: 220, width: "100%", borderRadius: 14 }} />}<Button title={`${item.likeCount || 0} likes · ${item.commentCount || 0} comments`} secondary onPress={() => setPost(item)} /></Card>)}<View style={{ flexDirection: "row", gap: 10 }}>{page > 1 && <Button title="Previous" secondary onPress={() => setPage(p => p - 1)} />}{feed.data?.pagination?.hasMore && <Button title="Next page" secondary onPress={() => setPage(p => p + 1)} />}</View></Screen>;
}
function PostDetail({ post, back, own }: { post: Post; back(): void; own: boolean }) {
  const comments = useResource<{ data: Comment[] }>(`/community/posts/${post.id}/comments`);
  const [content, setContent] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [panel, setPanel] = useState(""); const [draft, setDraft] = useState(post.content); const [display, setDisplay] = useState(post.content); const [reason, setReason] = useState("Misinformation"); const [liked, setLiked] = useState(false); const [saved, setSaved] = useState(false); const [reply, setReply] = useState<Comment>();
  useBack(Boolean(panel || reply), () => { setPanel(""); setReply(undefined); });
  async function action(path: string, body: unknown, method = "POST") {
    if (busy) return; setBusy(true); setError(""); setNotice("");
    try { const result = await api.request<{ liked?: boolean; bookmarked?: boolean }>(`/community/posts/${post.id}${path}`, { method, body });
      if (method === "DELETE") { back(); return; }
      if (method === "PUT") { setDisplay(draft.trim()); setPanel(""); setNotice("Post updated."); }
      else if (path === "/report") { setPanel(""); setNotice(previewEnabled ? "Report recorded in preview only." : "Report submitted."); }
      else if (result.bookmarked !== undefined) setSaved(result.bookmarked);
      else if (result.liked !== undefined) setLiked(result.liked);
      else { setContent(""); comments.reload(); setNotice("Comment added."); }
    } catch (e) { setError(e instanceof Error ? e.message : "Could not update."); } finally { setBusy(false); }
  }
  async function sendReply() { if (busy || !content.trim() || !reply) return; setBusy(true); setError(""); try { await api.request(`/community/comments/${reply.id}/reply`, { method: "POST", body: { content: content.trim() } }); setReply(undefined); setContent(""); comments.reload(); } catch (e) { setError(e instanceof Error ? e.message : "Could not reply."); } finally { setBusy(false); } }
  if (panel) return <Screen title={panel === "edit" ? "Edit post" : panel === "delete" ? "Delete post" : panel === "author" ? "Community profile" : "Report post"} back={() => { setPanel(""); setError(""); }}>{panel === "edit" ? <><Field label="Edit your update" value={draft} onChangeText={setDraft} multiline maxLength={5000} /><Button title="Save changes" busy={busy} disabled={!draft.trim()} onPress={() => void action("", { content: draft.trim(), type: post.type }, "PUT")} /></> : panel === "delete" ? <><Heading>Delete this post?</Heading><Body>This cannot be undone. Your post will be removed from the community.</Body><Button title="Delete post" busy={busy} onPress={() => void action("", undefined, "DELETE")} /><Button title="Keep post" secondary onPress={() => setPanel("")} /></> : panel === "author" ? <><Empty icon="person-circle-outline" title={post.author?.name || "Community member"} detail="Community member" /><Card><Heading>Recent update</Heading><Body>{display}</Body></Card><Button title="Back to post" secondary onPress={() => setPanel("")} /></> : <><Heading>Why are you reporting this?</Heading><Choices options={["Misinformation", "Inappropriate", "Spam", "Harassment"]} value={reason} onChange={setReason} /><Body>Your report is sent for review.</Body><Button title="Submit report" busy={busy} onPress={() => void action("/report", { reason: reason.toLowerCase() })} /></>}<ErrorText message={error} /></Screen>;
  return <Screen title="Conversation" back={back}><Card><Button title={post.author?.name || "Community member"} secondary onPress={() => setPanel("author")} /><Body>{new Date(post.createdAt).toLocaleDateString()}</Body><Body>{display}</Body>{post.imageUrl && <Image source={{ uri: post.imageUrl }} style={{ height: 220, borderRadius: 16 }} />}</Card><ErrorText message={error} />{!!notice && <Body>{notice}</Body>}<View style={{ flexDirection: "row", flexWrap: "wrap", gap: 8 }}><Button title={liked ? "Liked ♥" : "Like"} secondary={!liked} disabled={busy} onPress={() => void action("/engagement", { action: "like" })} /><Button title={saved ? "Saved" : "Save"} secondary={!saved} disabled={busy} onPress={() => void action("/bookmark", {})} /><Button title="Share" secondary onPress={() => void Share.share({ message: `${display}\n${webOrigin}/community` }).catch(() => setError("Could not share."))} /><Button title="Report" secondary onPress={() => setPanel("report")} />{own && <><Button title="Edit" secondary onPress={() => setPanel("edit")} /><Button title="Delete" secondary onPress={() => setPanel("delete")} /></>}</View><Heading>Comments</Heading><ResourceState {...comments} />{comments.data?.data.length === 0 && <Body>Start the conversation. Be the first to comment.</Body>}{comments.data?.data.map(comment => <Card key={comment.id}><Heading>{comment.author?.name || "Community member"}</Heading><Body>{comment.content}</Body>{comment.replies?.map(r => <View key={r.id} style={{ paddingLeft: 16 }}><Body>{r.author?.name}: {r.content}</Body></View>)}<Button title="Reply" secondary onPress={() => { setReply(comment); setContent(""); }} /></Card>)}{reply && <><Body>Replying to {reply.author?.name}</Body><Button title="Cancel reply" secondary onPress={() => { setReply(undefined); setContent(""); }} /></>}<Field label={reply ? "Your reply" : "Add a comment"} value={content} onChangeText={setContent} multiline maxLength={2000} /><Button title={reply ? "Send reply" : "Comment"} busy={busy} disabled={!content.trim()} onPress={() => reply ? void sendReply() : void action("/engagement", { action: "comment", content: content.trim() })} /></Screen>;
}
