import { validBookingDate } from "./booking-validation";
import { useEffect, useState } from "react";
import { Image, Platform, Text, View } from "react-native";
import DateTimePicker from "@react-native-community/datetimepicker";
import { api, type Appointment, type CareItem, type Profile } from "./api";
import { useSession } from "./session";
import * as Crypto from "expo-crypto";
import { type Navigate } from "./home";
import { Choices } from "./care";
import { pickImage } from "./media";
import { previewEnabled } from "./preview";
import { Body, Button, Card, colors, Empty, ErrorText, Field, Heading, ResourceState, Row, Screen, useResource } from "./ui";
export function Health({ navigate }: { navigate: Navigate }) {
  const { session } = useSession(); const [filter, setFilter] = useState("Current");
  const result = useResource<{ appointments: Appointment[] }>("/appointments");
  const items = (result.data?.appointments || []).filter(a => filter === "Current" ? ["approved", "pending_approval"].includes(a.status) : !["approved", "pending_approval"].includes(a.status));
  return <Screen title="My Health" subtitle="YOUR CARE, IN ONE PLACE"><Card><Heading>Hello, {session?.user.name.split(" ")[0]}</Heading><Body>Keep your health details and consultations together.</Body><Row title="Health profile" detail="Personal details, vitals & medical history" icon="shield-checkmark-outline" onPress={() => navigate({ name: "edit-profile" })} /><Row title="Medical records" detail="Reports and documents" icon="folder-open-outline" onPress={() => navigate({ name: "records" })} /></Card><Button title="Book an appointment" icon="add" onPress={() => navigate({ name: "care", kind: "doctors" })} /><Heading>Appointments</Heading><Choices options={["Current", "Past"]} value={filter} onChange={setFilter} /><ResourceState {...result} />{!result.loading && !result.error && items.length === 0 && <Empty title={`No ${filter.toLowerCase()} appointments`} detail="Your consultation requests and history will appear here." />}{items.map(item => <Card key={item.id}><Status value={item.status} /><Heading>{item.doctorName}</Heading><Body>{item.hospitalName}</Body><Body>{new Date(item.appointmentDate).toLocaleDateString("en-IN")} · {item.appointmentTime}</Body><Body>{item.appointmentMode === "video" ? "Video consultation" : "In person"}</Body><Button title="View appointment" secondary onPress={() => navigate({ name: "appointment", id: item.id })} /></Card>)}</Screen>;
}
function Status({ value }: { value: string }) { return <View style={{ alignSelf: "flex-start", backgroundColor: value === "completed" || value === "approved" ? "#DCFCE7" : "#FEF3C7", borderRadius: 20, paddingHorizontal: 12, paddingVertical: 7 }}><Text style={{ color: colors.ink, fontSize: 12, textTransform: "capitalize" }}>{value.replaceAll("_", " ")}</Text></View>; }
export function AppointmentDetail({ id, navigate, back }: { id: string; navigate: Navigate; back(): void }) {
  const result = useResource<{ appointments: Appointment[] }>("/appointments"); const item = result.data?.appointments.find(a => a.id === id); const [action, setAction] = useState("");
  return <Screen title="Appointment details" back={back}><ResourceState {...result} />{!result.loading && !result.error && !item && <Empty title="Appointment not found" />}{item && <><Card><Status value={item.status} /><Heading>{item.doctorName}</Heading><Body>{item.hospitalName}</Body><Body>{new Date(item.appointmentDate).toLocaleDateString("en-IN")} · {item.appointmentTime}</Body><Body>{item.appointmentMode === "video" ? "Video consultation" : "In person"}</Body><Body>Reference: {item.id}</Body></Card><Card><Heading>Reason for visit</Heading><Body>{item.reason || "No reason added"}</Body></Card>{["approved", "pending_approval"].includes(item.status) ? <><Body>Your provider confirms availability. A pending request is not a confirmed appointment.</Body><Button title="Reschedule" secondary onPress={() => setAction("Reschedule appointment")} /><Button title="Cancel appointment" secondary onPress={() => setAction("Cancel appointment")} />{item.appointmentMode === "video" && <Button title="Join consultation" onPress={() => setAction("Video consultation")} />}</> : <Button title="Book again" onPress={() => navigate(item.doctorId ? { name: "booking", id: String(item.doctorId) } : { name: "care", kind: "doctors" })} />}<Button title="View reports & prescriptions" secondary onPress={() => navigate({ name: "records" })} />{action && <Card><Heading>{action}</Heading><Body>{previewEnabled ? "This preview shows the appointment action. No appointment has been changed and no call will start." : "This service is not connected yet. Contact your provider for assistance."}</Body><Button title="Contact support" secondary onPress={() => navigate({ name: "support" })} /><Button title="Close" secondary onPress={() => setAction("")} /></Card>}</>}</Screen>;
}
export function Records({ navigate, back }: { navigate: Navigate; back(): void }) {
  const [image, setImage] = useState<string>(); const [error, setError] = useState("");
  async function select() { try { const picked = await pickImage(); if (picked) setImage(picked.dataUrl); } catch (e) { setError(e instanceof Error ? e.message : "Could not select record."); } }
  return <Screen title="Medical records" back={back}><Row title="AI reports" detail="Conversation summaries, clearly marked as AI generated" icon="sparkles-outline" onPress={() => navigate({ name: "reports" })} /><Card><Heading>Prescriptions & documents</Heading><Body>Keep a copy of a prescription or report ready to review.</Body><Button title="Select a record image" secondary icon="cloud-upload-outline" onPress={() => void select()} />{image ? <><Image source={{ uri: image }} style={{ width: "100%", height: 280, borderRadius: 16 }} resizeMode="contain" /><Body>Selected for preview only. This file has not been uploaded or saved.</Body><Button title="Remove selected record" secondary onPress={() => setImage(undefined)} /></> : <Empty icon="document-text-outline" title="No documents uploaded" detail="Document storage will be available when connected." />}<ErrorText message={error} /></Card></Screen>;
}
export function Booking({ doctorId, back, complete }: { doctorId: string; back(): void; complete(): void }) {
  const { session } = useSession(); const profile = useResource<Profile>(`/users/${session!.user.id}`); const doctor = useResource<{ data: CareItem }>(`/doctors/${doctorId}`);
  const [step, setStep] = useState(1); const [form, setForm] = useState({ fullName: "", age: "", gender: "female", phoneNumber: "", height: "", weight: "" });
  const [date, setDate] = useState(""); const [time, setTime] = useState(""); const [reason, setReason] = useState(""); const [mode, setMode] = useState("In person");
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(false); const [requestId] = useState(() => Crypto.randomUUID()); const [picker, setPicker] = useState<"date" | "time" | null>(null);
  useEffect(() => { if (profile.data) setForm({ fullName: profile.data.name, age: String(profile.data.age || ""), gender: profile.data.gender || "female", phoneNumber: profile.data.phoneNumber || "", height: profile.data.height || "", weight: profile.data.weight || "" }); }, [profile.data]);
  function next() {
    setError("");
    if (step === 1 && (!form.fullName.trim() || !/^\+?[\d\s-]{10,16}$/.test(form.phoneNumber) || !/^\d{1,3}$/.test(form.age) || Number(form.age) > 130)) { setError("Enter your name, a valid phone number and age (0–130)."); return; }
    if (step === 2 && (!validBookingDate(date) || !/^(0?[1-9]|1[0-2]):[0-5]\d (AM|PM)$/i.test(time.trim()))) { setError("Choose a valid date today or later and a time such as 10:30 AM."); return; }
    setStep(s => s + 1);
  }
  async function submit() {
    if (busy || success) return; setBusy(true); setError("");
    try { await api.request("/appointments", { method: "POST", body: { requestId, doctorId: Number(doctorId), selectedDate: date, selectedTimeSlot: time.trim().toUpperCase(), appointmentType: mode === "Video" ? "video" : "in-person", ...form, age: Number(form.age), additionalComments: reason.trim() } }); setSuccess(true); }
    catch (e) { setError(e instanceof Error ? e.message : "Could not request appointment."); } finally { setBusy(false); }
  }
  return <Screen key={step} title={success ? "Request received" : "Book appointment"} subtitle={success ? "YOUR NEXT STEP TO CARE" : `STEP ${step} OF 3`} back={() => { if (step > 1 && !success) { setStep(s => s - 1); setError(""); } else back(); }}>{success ? <><Empty icon="checkmark-circle-outline" title={previewEnabled ? "Preview request created" : "Awaiting approval"} detail={previewEnabled ? "Saved in this preview only. No provider has been contacted." : "Your provider will review the request. You’ll see updates in My Health."} /><Card><Heading>{doctor.data?.data?.name}</Heading><Body>{date} · {time}</Body><Body>{mode}</Body></Card><Button title="View appointments" onPress={complete} /></> : <><View style={{ flexDirection: "row", gap: 8 }}>{[1, 2, 3].map(n => <View key={n} style={{ height: 4, flex: 1, borderRadius: 4, backgroundColor: n <= step ? colors.deep : colors.line }} />)}</View><ResourceState {...profile} /><ResourceState {...doctor} />{doctor.data?.data && <Card><Heading>{doctor.data.data.name}</Heading><Body>{doctor.data.data.specialty} · {doctor.data.data.hospitalName || doctor.data.data.hospital_name}</Body></Card>}
    {step === 1 && <><Heading>Patient identity</Heading><Body>Check your details before choosing a time.</Body>{([['fullName', 'Full name'], ['age', 'Age'], ['phoneNumber', 'Phone number'], ['height', 'Height (cm) · optional'], ['weight', 'Weight (kg) · optional']] as const).map(([key, label]) => <Field key={key} label={label} value={form[key]} keyboardType={key === "fullName" ? "default" : key === "phoneNumber" ? "phone-pad" : "numeric"} onChangeText={value => setForm(f => ({ ...f, [key]: value }))} />)}<Heading>Gender</Heading><Choices options={["female", "male", "other"]} value={form.gender} onChange={gender => setForm(f => ({ ...f, gender }))} /><Field label="Reason for consultation" value={reason} onChangeText={setReason} multiline maxLength={2000} /></>}
    {step === 2 && <><Heading>Choose your consultation</Heading><Choices options={["In person", "Video"]} value={mode} onChange={setMode} /><Body>Select your preferred date and time. Availability is confirmed by the provider.</Body>{Platform.OS === "web" ? <><Field label="Date · YYYY-MM-DD" value={date} onChangeText={setDate} placeholder="2026-09-20" /><Field label="Preferred time" value={time} onChangeText={setTime} placeholder="10:30 AM" /></> : <><Button title={date || "Choose date"} secondary onPress={() => setPicker("date")} /><Button title={time || "Choose time"} secondary onPress={() => setPicker("time")} />{picker && <DateTimePicker mode={picker} value={new Date()} minimumDate={picker === "date" ? new Date() : undefined} onChange={(event, value) => { const chosen = picker; setPicker(null); if (event.type !== "set" || !value) return; if (chosen === "date") setDate(`${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}`); else setTime(`${value.getHours() % 12 || 12}:${String(value.getMinutes()).padStart(2,"0")} ${value.getHours() >= 12 ? "PM" : "AM"}`); }} />}</>}</>}
    {step === 3 && <><Heading>Review your request</Heading><Card><Body>{form.fullName} · {form.age} years · {form.gender}</Body><Body>{form.phoneNumber}</Body><Body>{date} · {time} · {mode}</Body><Body>{reason || "No reason added"}</Body><Heading>Consultation fee</Heading><Body>{doctor.data?.data?.consultationFees != null || doctor.data?.data?.consultation_fees != null ? `₹${doctor.data.data.consultationFees ?? doctor.data.data.consultation_fees}` : "Confirm with provider"}</Body><Body>No payment is collected here.</Body></Card><Button title="Edit patient details" secondary onPress={() => setStep(1)} /><Button title="Change date or time" secondary onPress={() => setStep(2)} /></>}
    <ErrorText message={error} /><Button title={step === 3 ? previewEnabled ? "Create preview request" : "Send request" : "Continue"} busy={busy} disabled={!profile.data || !doctor.data?.data} onPress={() => step === 3 ? void submit() : next()} /></>}</Screen>;
}
