import { useState } from "react";
import { Image, Linking, Share, Text, View } from "react-native";
import { labTests } from "./lab-data";
import { privacySections } from "./privacy-data";
import { type Navigate } from "./home";
import { Body, Button, Card, colors, Empty, ErrorText, Field, Glyph, Heading, Row, Screen } from "./ui";
export function LabTests({ navigate, back }: { navigate: Navigate; back(): void }) {
  const [query, setQuery] = useState(""); const tests = labTests.filter(t => t.name.toLowerCase().includes(query.toLowerCase()));
  return <Screen title="Tests & packages" subtitle="PATHOLOGY" back={back}><Body>Browse the web app’s sample test catalogue. Confirm prices and availability with the lab.</Body><Field label="Search tests" value={query} onChangeText={setQuery} placeholder="CBC, thyroid, blood sugar…" />{!tests.length && <Empty title="No tests found" />}{tests.map(test => <Card key={test.name}><View style={{ flexDirection: "row", alignItems: "center", gap: 14 }}><Image source={require("../../assets/web/pathlab.png")} style={{ width: 60, height: 60 }} /><View style={{ flex: 1 }}><Heading>{test.name}</Heading><Body>{test.includeTests.length} parameters</Body></View></View><Text style={{ color: colors.deep, fontWeight: "700" }}>Sample price ₹{test.price}</Text><Button title="View test details" secondary onPress={() => navigate({ name: "lab-test", query: test.name })} /></Card>)}</Screen>;
}
export function LabTest({ name, back, navigate }: { name: string; back(): void; navigate: Navigate }) {
  const test = labTests.find(t => t.name === name); const [error, setError] = useState("");
  return <Screen title="Test details" back={back}>{test ? <><Image source={require("../../assets/web/pathlab.png")} style={{ width: "100%", height: 160 }} resizeMode="contain" /><Heading>{test.name}</Heading><Body>Sample catalogue price: ₹{test.price}. Confirm with your lab before booking.</Body><Card><Heading>Included parameters</Heading>{test.includeTests.map(item => <Body key={item}>• {item}</Body>)}</Card><Body>Lab booking is not connected yet. Contact support for help finding a provider.</Body><Button title="Contact support" onPress={() => navigate({ name: "support" })} /><Button title="Share test" secondary icon="share-outline" onPress={() => void Share.share({ message: `${test.name}\nIncluded: ${test.includeTests.join(", ")}` }).catch(() => setError("Could not share test."))} /><ErrorText message={error} /></> : <Empty title="Test not found" />}</Screen>;
}
export function Support({ back }: { back(): void }) {
  const [error, setError] = useState("");
  const open = (url: string) => void Linking.openURL(url).catch(() => setError("Could not open this app. Use the contact details shown below."));
  return <Screen title="Help & Support" back={back}><View style={{ alignItems: "center", paddingVertical: 18, gap: 18 }}><Image source={require("../../assets/auth/virujlogo.png")} style={{ width: 90, height: 90 }} resizeMode="contain" /><Heading>We’re here to help</Heading><Body>Reach out to the Viruj support team.</Body></View><Card><Row title="Email us" detail="help@virujhealth.com" icon="mail-outline" onPress={() => open("mailto:help@virujhealth.com")} /><Row title="Call us" detail="+91 7982958828" icon="call-outline" onPress={() => open("tel:+917982958828")} /></Card><Body>Monday – Saturday, 9 AM – 6 PM IST</Body><ErrorText message={error} /></Screen>;
}
export function Privacy({ back, navigate }: { back(): void; navigate: Navigate }) { return <Screen title="Privacy & Security" back={back}><View style={{ alignItems: "center", gap: 15, padding: 20 }}><Glyph name="shield-checkmark-outline" size={44} color="#059669" /><Heading>Viruj Health Privacy Policy</Heading><Body>How Viruj Health Technologies collects, uses, stores and shares your information.</Body></View>{privacySections.map(([title, content]) => <Card key={title}><Heading>{title}</Heading><Body>{content}</Body></Card>)}<Row title="Contact us about privacy" detail="help@virujhealth.com · India" icon="mail-outline" onPress={() => navigate({ name: "support" })} /><Row title="Request account deletion" icon="trash-outline" onPress={() => navigate({ name: "delete-account" })} /></Screen>; }
export function ServiceInfo({ name, back, navigate }: { name: string; back(): void; navigate: Navigate }) { return <Screen title={name} back={back}><Empty icon="medical-outline" title={`${name} is coming soon`} detail="This service is not available yet. You can explore hospitals and doctors in the meantime." /><Button title="Explore hospitals" onPress={() => navigate({ name: "care", kind: "hospitals" })} /><Button title="Find a doctor" secondary onPress={() => navigate({ name: "care", kind: "doctors" })} /></Screen>; }
