// Mirrors pathlabs/page, pathlabs/[id], pathalabcard, offer-carousel and test-list.
import { useEffect, useState } from "react";
import { Image, Linking, Pressable, ScrollView, Share, View } from "react-native";
import { type CareItem } from "./api";
import { type Navigate } from "./home";
import { SearchInput, Stars } from "./web-controls";
import { labTests } from "./lab-data";
import { Body, Button, Card, Empty, ErrorText, Glyph, Heading, ResourceState, Screen, useResource } from "./ui";
export function Pathlabs({ navigate, back }: { navigate: Navigate; back(): void }) {
  const result = useResource<{ data: CareItem[] }>("/pathlabs"); const [query, setQuery] = useState(""); const [sort, setSort] = useState("rating"); const [discount, setDiscount] = useState(false);
  const labs = (result.data?.data || []).filter(l => `${l.name} ${l.city} ${l.area}`.toLowerCase().includes(query.toLowerCase()) && (!discount || (l.reviewCount || 0) >= 200)).slice().sort((a, b) => sort === "rating" ? Number(b.rating || 0) - Number(a.rating || 0) : 0);
  return <Screen title="Pathlabs" back={back}><SearchInput placeholder="Search pathlabs, city, or area..." value={query} onChange={setQuery} /><ScrollView horizontal contentContainerStyle={{ gap: 12 }}><Button title="Sort by Rating" secondary={sort !== "rating"} onPress={() => setSort("rating")} /><Button title="Sort by Distance" secondary={sort !== "distance"} onPress={() => setSort("distance")} /><Button title={discount ? "Showing Discounts" : "Show Discounts"} secondary={!discount} onPress={() => setDiscount(!discount)} /></ScrollView><ResourceState {...result} />{!result.loading && !result.error && !labs.length && <Body>No labs found with selected filters.</Body>}{labs.map(lab => <Pressable accessibilityRole="button" accessibilityLabel={`View ${lab.name}`} key={lab.id} onPress={() => navigate({ name: "detail", kind: "pathlabs", id: String(lab.id) })}><Card style={{ backgroundColor: "#F9FAFB", padding: 4, borderRadius: 8 }}><View style={{ flexDirection: "row", gap: 8 }}><Image source={lab.imageUrl ? { uri: lab.imageUrl } : require("../../assets/web/pathlab.png")} style={{ width: 80, height: 80, borderRadius: 8 }} resizeMode="contain" /><View style={{ flex: 1, gap: 6 }}><Heading style={{ fontSize: 16 }}>{lab.name}</Heading><Body>{lab.area}, {lab.city}</Body><Stars value={lab.rating} reviews={lab.reviewCount || 0} /><View style={{ flexDirection: "row", justifyContent: "space-between" }}><Body>₹{lab.startingPrice}</Body><Body style={{ fontSize: 12, paddingHorizontal: 8, backgroundColor: lab.isOpen ? "#DCFCE7" : "#FEE2E2", color: lab.isOpen ? "#15803D" : "#B91C1C", borderRadius: 12 }}>{lab.isOpen ? "Open" : "Closed"}</Body></View></View></View></Card></Pressable>)}</Screen>;
}
export function PathlabDetail({ id, back }: { id: string; back(): void }) {
  const result = useResource<{ data: CareItem }>(`/pathlabs/${id}`); const [liked, setLiked] = useState(false); const [error, setError] = useState(""); const lab = result.data?.data;
  return <Screen title="Pathlab Details" back={back}><ResourceState {...result} />{lab && <><Card style={{ backgroundColor: "#F9FAFB", padding: 8, borderRadius: 8, borderWidth: 2 }}><Image source={lab.imageUrl ? { uri: lab.imageUrl } : require("../../assets/web/pathlab.png")} style={{ width: "100%", aspectRatio: 4 / 3, borderRadius: 8 }} resizeMode="contain" /><Heading style={{ fontSize: 30, fontWeight: "800" }}>{lab.name}</Heading><Body>{lab.area}, {lab.city}</Body><Stars value={lab.rating} reviews={lab.reviewCount || 0} /><View style={{ flexDirection: "row", gap: 16 }}>{([['share-outline', 'Share'], [liked ? 'thumbs-up' : 'thumbs-up-outline', 'Like'], ['map-outline', 'Location']] as const).map(([icon, label]) => <Pressable key={label} accessibilityRole="button" accessibilityLabel={label} onPress={() => label === "Like" ? setLiked(!liked) : void (label === "Share" ? Share.share({ message: `${lab.name} · ${lab.area}, ${lab.city}` }) : Linking.openURL("https://maps.google.com")).catch(() => setError("Could not open this action."))} style={{ backgroundColor: "#DBEAFE", padding: 12, borderRadius: 30 }}><Glyph name={icon} color="#2563EB" size={20} /></Pressable>)}</View><Body style={{ color: "#374151", fontSize: 16, lineHeight: 25 }}>1. Blood Tests, 2. Biochemistry Tests, 3. Hormonal Tests, 4. Microbiology Tests, 5. Urine Tests, 6. Stool Tests, 7. Serology / Infectious Disease Panels, 8. Tumor Markers, 9. Pediatric/Neonatal Tests, 10. Health Checkup Packages Etc.</Body></Card><Offers /><TestList /><ErrorText message={error} /></>}{!result.loading && !result.error && !lab && <Empty title="Pathlab not found" />}</Screen>;
}
const offers = [
  ["Diagnostic Tests", "Get full body checkup with up to 50% Off", "Book Now", "#0D9488", require("../../assets/web/pathlab.png")],
  ["Dental Care", "Premium dental consultations. Save 30% today", "Book Appointment", "#9333EA", require("../../assets/web/hospital.png")],
  ["Eye Checkups", "Comprehensive vision tests by specialists", "Schedule Visit", "#059669", require("../../assets/web/clinics.png")],
  ["Heart Screening", "Advanced cardiac screening. Flat 40% off", "Get Tested", "#E11D48", require("../../assets/web/doctor.png")],
  ["Women's Wellness", "Specialized health packages for every stage", "Learn More", "#DB2777", require("../../assets/web/radiology.png")],
] as const;
function Offers() { const [index, setIndex] = useState(0); const [notice, setNotice] = useState(false); useEffect(() => { const timer = setInterval(() => setIndex(i => (i + 1) % offers.length), 5000); return () => clearInterval(timer); }, []); const offer = offers[index]!; return <View style={{ gap: 12 }}><Body style={{ alignSelf: "flex-start", backgroundColor: "#FFF1F2", color: "#DC2626", paddingHorizontal: 24, paddingVertical: 12, borderRadius: 30 }}>DISCOUNTS & OFFERS</Body><View style={{ minHeight: 144, padding: 16, borderRadius: 16, flexDirection: "row", backgroundColor: `${offer[3]}15`, gap: 16 }}><View style={{ flex: 1, gap: 5 }}><Body style={{ fontSize: 10 }}>● SPECIAL OFFER</Body><Heading>{offer[0]}</Heading><Body style={{ fontSize: 12 }}>{offer[1]}</Body><Pressable accessibilityRole="button" onPress={() => setNotice(true)} style={{ backgroundColor: offer[3], borderRadius: 24, padding: 8, alignSelf: "flex-start" }}><Body style={{ color: "white", fontSize: 12 }}>{offer[2]} ›</Body></Pressable></View><Image source={offer[4]} style={{ width: "35%", height: 112 }} resizeMode="contain" /></View>{notice && <Body>Offer booking is not available yet.</Body>}</View>; }
function TestList() { const [query, setQuery] = useState(""); const [added, setAdded] = useState<string[]>([]); const [error, setError] = useState(""); const filtered = labTests.filter(t => `${t.name} ${t.includeTests.join(" ")}`.toLowerCase().includes(query.toLowerCase())); return <View style={{ gap: 16 }}><SearchInput placeholder="Search for a test..." value={query} onChange={setQuery} />{filtered.map(test => <Card key={test.name} style={{ padding: 4, borderRadius: 8, backgroundColor: "#F9FAFB" }}><View style={{ flexDirection: "row", gap: 8 }}><Image source={require("../../assets/web/pathlab.png")} style={{ width: 96, height: 96, borderRadius: 8 }} /><View style={{ flex: 1, gap: 4 }}><View style={{ flexDirection: "row", alignItems: "flex-start" }}><Heading style={{ flex: 1 }}>{test.name}</Heading><Pressable accessibilityRole="button" accessibilityLabel={`Share ${test.name}`} style={{ padding: 8 }} onPress={() => void Share.share({ message: test.name }).catch(() => setError("Could not share test."))}><Glyph name="share-social-outline" size={16} color="#111827" /></Pressable></View><Body>Includes Tests: {test.includeTests.join(", ")}</Body><Body>⭐ {test.rating} ({test.reviewCount} Reviews)</Body><View style={{ flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", gap: 8, alignItems: "center" }}><Heading>₹ {test.price}</Heading><Button title={added.includes(test.name) ? "Added" : "Add Test"} onPress={() => setAdded(a => a.includes(test.name) ? a.filter(n => n !== test.name) : [...a, test.name])} /></View></View></View></Card>)}{!filtered.length && <Body>No tests found for your search.</Body>}{added.length > 0 && <Body>Selection only. Test booking is not connected.</Body>}<ErrorText message={error} /></View>; }
