import { previewEnabled } from "./preview";
import { Choices } from "./care";
import { useEffect, useState } from "react";
import { Image, Text, View } from "react-native";
import { api, type Profile as ProfileData, webOrigin } from "./api";
import { useSession } from "./session";
import { pickImage } from "./media";
import { type Navigate } from "./home";
import { Body, Button, Card, colors, Empty, Glyph, ErrorText, Field, Heading, ResourceState, Row, Screen, useResource } from "./ui";
export function Profile({ navigate }: { navigate: Navigate }) {
  const { session, logout } = useSession(); const [error, setError] = useState(""); const [confirm, setConfirm] = useState(false);
  const profile = useResource<ProfileData>(`/users/${session!.user.id}`); const user = profile.data;
  return <Screen title="Profile" subtitle="YOUR PERSONAL HEALTH SPACE"><ResourceState {...profile} /><View style={{ backgroundColor: colors.deep, borderRadius: 28, padding: 24, gap: 18 }}><View style={{ flexDirection: "row", alignItems: "center", gap: 16 }}>{user?.image ? <Image source={{ uri: user.image }} style={{ width: 72, height: 72, borderRadius: 36 }} /> : <View style={{ width: 64, height: 64, backgroundColor: "#FFFFFF22", borderRadius: 32, alignItems: "center", justifyContent: "center" }}><Glyph name="person-outline" color="white" size={32} /></View>}<View style={{ flex: 1, gap: 6 }}><Text style={{ fontFamily: "Merienda", fontSize: 22, color: "white" }}>{user?.name || session!.user.name}</Text><Text style={{ color: "#FECACA", fontSize: 12 }}>{session!.user.email}</Text></View></View><Button title="Edit profile" secondary onPress={() => navigate({ name: "edit-profile" })} /></View><View style={{ flexDirection: "row", gap: 10 }}>{[["Blood group", user?.bloodGroup], ["Height", user?.height ? `${user.height} cm` : null], ["Weight", user?.weight ? `${user.weight} kg` : null]].map(([label, value]) => <View key={label} style={{ flex: 1, backgroundColor: "white", padding: 14, borderRadius: 18, gap: 8 }}><Text style={{ fontSize: 11, color: colors.muted }}>{label}</Text><Text style={{ fontWeight: "700", color: colors.deep, fontSize: 18 }}>{value || "—"}</Text></View>)}</View><Heading>Health & activity</Heading><Card><Row title="My Health Records" icon="heart-outline" onPress={() => navigate({ name: "health" })} /><Row title="AI reports" icon="document-text-outline" onPress={() => navigate({ name: "reports" })} /><Row title="Notifications" icon="notifications-outline" onPress={() => navigate({ name: "notifications" })} /></Card><Heading>Preferences & support</Heading><Card><Row title="App Feedback" icon="star-outline" onPress={() => navigate({ name: "feedback" })} /><Row title="Privacy & Security" icon="shield-checkmark-outline" onPress={() => navigate({ name: "privacy" })} /><Row title="Help & Support" icon="help-circle-outline" onPress={() => navigate({ name: "support" })} /><Row title="Delete account" icon="trash-outline" onPress={() => navigate({ name: "delete-account" })} /></Card><ErrorText message={error} />{confirm ? <Card><Heading>{previewEnabled ? "Exit preview?" : "Sign out?"}</Heading><Body>{previewEnabled ? "Your preview changes will reset next time." : "You can sign in again with your mobile number."}</Body><Button title={previewEnabled ? "Exit preview" : "Confirm sign out"} onPress={() => void logout().catch(() => setError("Could not sign out."))} /><Button title="Stay here" secondary onPress={() => setConfirm(false)} /></Card> : <Button title={previewEnabled ? "Exit UI preview" : "Sign out"} secondary onPress={() => setConfirm(true)} />}<Body>Viruj Health · Care that stays with you</Body></Screen>;
}
export function DeleteAccount({ back }: { back(): void }) {
  const [confirmation, setConfirmation] = useState(""); const [busy, setBusy] = useState(false); const [sent, setSent] = useState(false); const [error, setError] = useState("");
  async function submit() { if (busy || confirmation !== "DELETE") return; setBusy(true); setError(""); try { await api.request("/account-deletion", { method: "POST", body: { confirmation } }); setSent(true); } catch (e) { setError(e instanceof Error ? e.message : "Could not submit request."); } finally { setBusy(false); } }
  return <Screen title="Delete account" back={back}>{sent ? <><Empty icon="checkmark-circle-outline" title={previewEnabled ? "Preview request recorded" : "Request recorded"} detail={previewEnabled ? "No real account has been affected." : "Your request is pending review. Your account has not yet been deleted."} /><Button title="Back to profile" onPress={back} /></> : <><Body>Request deletion of your account and associated data. This submits a request for review.</Body><Field label="Type DELETE to confirm" value={confirmation} onChangeText={setConfirmation} autoCapitalize="characters" /><ErrorText message={error} /><Button title="Request deletion" busy={busy} disabled={confirmation !== "DELETE"} onPress={() => void submit()} /></>}</Screen>;
}
export function EditProfile({ back }: { back(): void }) {
  const { session } = useSession(); const profile = useResource<ProfileData>(`/users/${session!.user.id}`);
  const [form, setForm] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [saved, setSaved] = useState(false);
  useEffect(() => { if (profile.data) setForm(Object.fromEntries(Object.entries(profile.data).filter(([, value]) => typeof value === "string" || typeof value === "number").map(([key, value]) => [key, String(value)]))); }, [profile.data]);
  async function photo() { setError(""); try { const image = await pickImage(); if (image) { await api.request(`/users/${session!.user.id}`, { method: "PATCH", body: { image: image.dataUrl } }); profile.reload(); } } catch (e) { setError(e instanceof Error ? e.message : "Could not update photo."); } }
  async function save() {
    if (busy) return; if (!form.name?.trim()) { setError("Enter your name."); return; }
    const age = form.age ? Number(form.age) : null;
    if (age !== null && (!Number.isInteger(age) || age < 0 || age > 130)) { setError("Enter a valid age."); return; }
    setBusy(true); setError(""); setSaved(false);
    try { await api.request(`/users/${session!.user.id}`, { method: "PATCH", body: { ...Object.fromEntries(["name", "phoneNumber", "address", "bloodGroup", "height", "weight", "medicalHistory", "gender"].map(key => [key, form[key]?.trim() || null])), age, onboardingCompleted: true } }); setSaved(true); }
    catch (e) { setError(e instanceof Error ? e.message : "Could not save."); } finally { setBusy(false); }
  }
  return <Screen title="Edit profile" back={back}><ResourceState {...profile} />{profile.data && <><Card><Heading>Personal information</Heading><Body>Keep your details current for your next consultation.</Body>{profile.data.image && <Image source={{ uri: profile.data.image }} style={{ width: 80, height: 80, borderRadius: 40 }} />}</Card><Button title="Change photo" secondary onPress={() => void photo()} />{[["name", "Full name"], ["phoneNumber", "Phone"], ["age", "Age"], ["gender", "Gender · male, female, other"], ["bloodGroup", "Blood group"], ["height", "Height"], ["weight", "Weight"], ["address", "Address"], ["medicalHistory", "Medical history"]].map(([key, label]) => <Field key={key} label={label!} value={form[key!] || ""} onChangeText={value => { setSaved(false); setForm(f => ({ ...f, [key!]: value })); }} keyboardType={key === "age" ? "number-pad" : key === "phoneNumber" ? "phone-pad" : "default"} multiline={key === "medicalHistory"} autoCapitalize={key === "gender" ? "none" : "sentences"} />)}<ErrorText message={error} />{saved && <Body>Profile saved.</Body>}<Button title="Save changes" busy={busy} onPress={() => void save()} /></>}</Screen>;
}
export function Feedback({ back }: { back(): void }) {
  const [rating, setRating] = useState(0); const [text, setText] = useState(""); const [category, setCategory] = useState("App Design"); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [sent, setSent] = useState(false);
  async function submit() { if (busy || !rating) return; setBusy(true); setError(""); try { await api.request("/feedback", { method: "POST", body: { rating, feedback: text, category } }); setSent(true); } catch (e) { setError(e instanceof Error ? e.message : "Could not send."); } finally { setBusy(false); } }
  return <Screen title="App Feedback" back={back}>{sent ? <><Empty icon="heart-outline" title="Thank you!" detail={previewEnabled ? "Feedback saved in this preview only." : "Your feedback helps us improve your experience."} /><Button title="Back to profile" onPress={back} /></> : <><View style={{ alignItems: "center", gap: 16, paddingVertical: 24 }}><Glyph name="chatbubble-ellipses-outline" size={48} /><Heading>How are we doing?</Heading><Body>We would love to hear from you.</Body></View><Choices options={["1 ★", "2 ★", "3 ★", "4 ★", "5 ★"]} value={rating ? `${rating} ★` : ""} onChange={value => setRating(Number(value[0]))} /><Heading>What is your feedback about?</Heading><Choices options={["App Design", "Features", "Medical Service", "Privacy"]} value={category} onChange={setCategory} /><Field label="Tell us more" placeholder="What worked well? What could be better?" value={text} onChangeText={setText} multiline maxLength={3000} /><ErrorText message={error} /><Button title="Send feedback" disabled={!rating} onPress={() => void submit()} busy={busy} /></>}</Screen>;
}
