import { type Destination } from "./home";
// Each product page in virujhealthapp/src/app has a native review destination; mobile auth uses its own screen.
export const webPages: { path: string; destination: Destination }[] = [
  { path: "/", destination: { name: "home" } },
  { path: "/onboarding", destination: { name: "onboarding" } },
  { path: "/profile-setup", destination: { name: "profile-setup" } },
  { path: "/doctors", destination: { name: "care", kind: "doctors" } },
  { path: "/doctors/doctors-detail", destination: { name: "detail", kind: "doctors", id: "1" } },
  { path: "/hospitals", destination: { name: "care", kind: "hospitals" } },
  { path: "/hospitals/hospital-details", destination: { name: "detail", kind: "hospitals", id: "1" } },
  { path: "/department-page", destination: { name: "care", kind: "doctors", query: "Cardiac Sciences" } },
  { path: "/departments/[slug]/doctors", destination: { name: "department-doctors", query: "cardiac-sciences" } },
  { path: "/pathlabs", destination: { name: "care", kind: "pathlabs" } },
  { path: "/pathlabs/[id]", destination: { name: "detail", kind: "pathlabs", id: "1" } },
  { path: "/pathlabs/pathlab-details", destination: { name: "pathlab-placeholder" } },
  { path: "/booking-page", destination: { name: "booking", id: "1" } },
  { path: "/my-health", destination: { name: "health" } },
  { path: "/community", destination: { name: "community" } },
  { path: "/ask-ai", destination: { name: "chat" } },
  { path: "/notification-page", destination: { name: "notifications" } },
  { path: "/profile", destination: { name: "profile" } },
  { path: "/profile/edit", destination: { name: "edit-profile" } },
  { path: "/profile/feedback", destination: { name: "feedback" } },
  { path: "/privacy-policy", destination: { name: "privacy" } },
  { path: "/account-deletion", destination: { name: "public-deletion" } },
];
