import { useState } from "react";
import { Modal, Pressable, ScrollView, Text, View } from "react-native";
import { Body, colors, Glyph, Heading, type Icon } from "./ui";
export function SelectField({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange(value: string): void }) {
  const [open, setOpen] = useState(false);
  return <View style={{ gap: 8 }}><Body style={{ color: "#111827", fontSize: 14 }}>{label}</Body><Pressable accessibilityRole="button" accessibilityLabel={label} onPress={() => setOpen(true)} style={{ minHeight: 44, borderWidth: 1, borderColor: "#E5E7EB", borderRadius: 8, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }}><Body>{value || `Select ${label.toLowerCase()}`}</Body><Glyph name="chevron-down" color="#9CA3AF" size={16} /></Pressable><Modal visible={open} transparent animationType="fade" onRequestClose={() => setOpen(false)}><Pressable accessibilityLabel="Close selection" style={{ flex: 1, backgroundColor: "#00000055", justifyContent: "center", padding: 24 }} onPress={() => setOpen(false)}><View style={{ backgroundColor: "white", padding: 16, borderRadius: 16, maxHeight: "75%" }}><Heading>{label}</Heading><ScrollView>{options.map(option => <Pressable key={option} accessibilityRole="radio" accessibilityState={{ checked: value === option }} onPress={() => { onChange(option); setOpen(false); }} style={{ minHeight: 48, padding: 12, flexDirection: "row", justifyContent: "space-between" }}><Body>{option}</Body>{value === option && <Glyph name="checkmark" size={20} />}</Pressable>)}</ScrollView></View></Pressable></Modal></View>;
}
export function IconAction({ icon, label, onPress, color = "#6B7280" }: { icon: Icon; label: string; onPress(): void; color?: string }) { return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={{ minWidth: 40, minHeight: 40, alignItems: "center", justifyContent: "center" }}><Glyph name={icon} color={color} size={20} /></Pressable>; }
export function CheckRow({ value, onChange, label }: { value: boolean; onChange(value: boolean): void; label: string }) { return <Pressable accessibilityRole="checkbox" accessibilityState={{ checked: value }} onPress={() => onChange(!value)} style={{ flexDirection: "row", gap: 16, padding: 16, borderRadius: 16, borderWidth: 1, borderColor: value ? "#FECACA" : "#F3F4F6", backgroundColor: value ? "#FEF2F2" : "white" }}><Glyph name={value ? "checkbox" : "square-outline"} size={20} color={value ? "#DC2626" : "#9CA3AF"} /><Body style={{ flex: 1, color: "#374151" }}>{label}</Body></Pressable>; }
export function Range({ label, value, onChange, min, max, unit }: { label: string; value: number; onChange(value: number): void; min: number; max: number; unit: string }) {
  const [width, setWidth] = useState(1); const update = (x: number) => onChange(Math.max(min, Math.min(max, Math.round(min + x / width * (max - min)))));
  return <View style={{ gap: 16 }}><View style={{ flexDirection: "row", justifyContent: "space-between" }}><Body style={{ fontSize: 10, textTransform: "uppercase", letterSpacing: 2 }}>{label}</Body><Text style={{ fontFamily: "Merienda", fontSize: 20, fontWeight: "800" }}>{value} <Text style={{ fontSize: 10, color: "#9CA3AF" }}>{unit}</Text></Text></View><View accessibilityRole="adjustable" accessibilityLabel={label} accessibilityValue={{ min, max, now: value, text: `${value} ${unit}` }} accessibilityActions={[{ name: "increment" }, { name: "decrement" }]} onAccessibilityAction={e => onChange(Math.max(min, Math.min(max, value + (e.nativeEvent.actionName === "increment" ? 1 : -1))))} onLayout={e => setWidth(e.nativeEvent.layout.width)} onStartShouldSetResponder={() => true} onMoveShouldSetResponder={() => true} onResponderGrant={e => update(e.nativeEvent.locationX)} onResponderMove={e => update(e.nativeEvent.locationX)} style={{ height: 40, justifyContent: "center" }}><View style={{ height: 6, backgroundColor: "#F3F4F6", borderRadius: 4 }}><View style={{ height: 6, width: `${(value-min)/(max-min)*100}%`, backgroundColor: colors.deep, borderRadius: 4 }} /><View style={{ position: "absolute", top: -7, left: `${(value-min)/(max-min)*100}%`, marginLeft: -10, width: 20, height: 20, borderWidth: 2, borderColor: colors.deep, backgroundColor: "white", borderRadius: 10 }} /></View></View></View>;
}
