import { useState, type ReactNode } from "react";
import { Image, Modal, Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { Body, colors, Glyph, Heading, type Icon } from "./ui";
export function SelectField({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange(value: string): void }) {
  const [open, setOpen] = useState(false);
  return <View style={{ gap: 8 }}><Body style={{ color: "#111827", fontSize: 14 }}>{label}</Body><Pressable accessibilityRole="button" accessibilityLabel={label} onPress={() => setOpen(true)} style={{ minHeight: 44, borderWidth: 1, borderColor: "#E5E7EB", borderRadius: 8, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }}><Body>{value || `Select ${label.toLowerCase()}`}</Body><Glyph name="chevron-down" color="#9CA3AF" size={16} /></Pressable><Modal visible={open} transparent animationType="fade" onRequestClose={() => setOpen(false)}><Pressable accessibilityLabel="Close selection" style={{ flex: 1, backgroundColor: "#00000055", justifyContent: "center", padding: 24 }} onPress={() => setOpen(false)}><View style={{ backgroundColor: "white", padding: 16, borderRadius: 16, maxHeight: "75%" }}><Heading>{label}</Heading><ScrollView>{options.map(option => <Pressable key={option} accessibilityRole="radio" accessibilityState={{ checked: value === option }} onPress={() => { onChange(option); setOpen(false); }} style={{ minHeight: 48, padding: 12, flexDirection: "row", justifyContent: "space-between" }}><Body>{option}</Body>{value === option && <Glyph name="checkmark" size={20} />}</Pressable>)}</ScrollView></View></Pressable></Modal></View>;
}
export function IconAction({ icon, label, onPress, color = "#6B7280" }: { icon: Icon; label: string; onPress(): void; color?: string }) { return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={{ minWidth: 40, minHeight: 40, alignItems: "center", justifyContent: "center" }}><Glyph name={icon} color={color} size={20} /></Pressable>; }
export function CheckRow({ value, onChange, label, compact }: { value: boolean; onChange(value: boolean): void; label: string; compact?: boolean }) { return <Pressable accessibilityRole="checkbox" accessibilityState={{ checked: value }} onPress={() => onChange(!value)} style={{ flexDirection: "row", gap: compact ? 8 : 16, padding: compact ? 0 : 16, borderRadius: 16, borderWidth: compact ? 0 : 1, borderColor: value ? "#FECACA" : "#F3F4F6", backgroundColor: !compact && value ? "#FEF2F2" : "white" }}><Glyph name={value ? "checkbox" : "square-outline"} size={20} color={value ? "#DC2626" : "#9CA3AF"} /><Body style={{ flex: compact ? undefined : 1, fontSize: compact ? 12 : 14, color: "#374151" }}>{label}</Body></Pressable>; }
export function Range({ label, value, onChange, min, max, unit }: { label: string; value: number; onChange(value: number): void; min: number; max: number; unit: string }) {
  const [width, setWidth] = useState(1); const update = (x: number) => onChange(Math.max(min, Math.min(max, Math.round(min + x / width * (max - min)))));
  return <View style={{ gap: 16 }}><View style={{ flexDirection: "row", justifyContent: "space-between" }}><Body style={{ fontSize: 10, textTransform: "uppercase", letterSpacing: 2 }}>{label}</Body><Text style={{ fontFamily: "Merienda", fontSize: 20, fontWeight: "800" }}>{value} <Text style={{ fontSize: 10, color: "#9CA3AF" }}>{unit}</Text></Text></View><View accessibilityRole="adjustable" accessibilityLabel={label} accessibilityValue={{ min, max, now: value, text: `${value} ${unit}` }} accessibilityActions={[{ name: "increment" }, { name: "decrement" }]} onAccessibilityAction={e => onChange(Math.max(min, Math.min(max, value + (e.nativeEvent.actionName === "increment" ? 1 : -1))))} onLayout={e => setWidth(e.nativeEvent.layout.width)} onStartShouldSetResponder={() => true} onMoveShouldSetResponder={() => true} onResponderGrant={e => update(e.nativeEvent.locationX)} onResponderMove={e => update(e.nativeEvent.locationX)} style={{ height: 40, justifyContent: "center" }}><View style={{ height: 6, backgroundColor: "#F3F4F6", borderRadius: 4 }}><View style={{ height: 6, width: `${(value-min)/(max-min)*100}%`, backgroundColor: colors.deep, borderRadius: 4 }} /><View style={{ position: "absolute", top: -7, left: `${(value-min)/(max-min)*100}%`, marginLeft: -10, width: 20, height: 20, borderWidth: 2, borderColor: colors.deep, backgroundColor: "white", borderRadius: 10 }} /></View></View></View>;
}

export function Sheet({ title, close, children }: { title: string; close(): void; children: ReactNode }) { return <Modal transparent animationType="slide" onRequestClose={close}><View style={{ flex: 1, justifyContent: "flex-end", backgroundColor: "#00000080" }}><Pressable accessibilityLabel="Close dialog" onPress={close} style={{ flex: 1 }} /><View style={{ maxHeight: "85%", backgroundColor: "white", borderTopLeftRadius: 24, borderTopRightRadius: 24, overflow: "hidden" }}><View style={{ padding: 16, backgroundColor: "#FFF1F2", flexDirection: "row", alignItems: "center", justifyContent: "space-between" }}><Heading style={{ color: "#B91C1C", fontSize: 20 }}>{title}</Heading><IconAction label={`Close ${title}`} icon="close" onPress={close} /></View><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ padding: 24, paddingBottom: 32, gap: 16 }}>{children}</ScrollView></View></View></Modal>; }

export function Avatar({ name, image }: { name?: string; image?: string | null }) { return <View style={{ width: 40, height: 40, borderRadius: 20, overflow: "hidden", backgroundColor: "#FEE2E2", justifyContent: "center", alignItems: "center" }}>{image ? <Image source={{ uri: image }} style={{ width: 40, height: 40 }} /> : <Body style={{ color: "#991B1B", fontWeight: "700" }}>{name?.[0] || "U"}</Body>}</View>; }

export function SearchInput({ placeholder, value, onChange }: { placeholder: string; value: string; onChange(value: string): void }) { return <View style={{ flexDirection: "row", gap: 12, alignItems: "center", borderWidth: 1, borderColor: "#E5E7EB", backgroundColor: "white", borderRadius: 16, paddingHorizontal: 16 }}><Glyph name="search-outline" size={20} color="#9CA3AF" /><TextInput accessibilityLabel={placeholder} placeholder={placeholder} value={value} onChangeText={onChange} style={{ flex: 1, minHeight: 56, fontFamily: "Merienda", fontSize: 14, color: "#111827" }} placeholderTextColor="#9CA3AF" /></View>; }
export function Stars({ value, reviews }: { value?: number | string; reviews?: number }) { return <View style={{ flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 3 }}>{Array.from({ length: 5 }, (_, i) => <Glyph key={i} name={i < Math.floor(Number(value || 0)) ? "star" : "star-outline"} color={i < Math.floor(Number(value || 0)) ? "#FACC15" : "#D1D5DB"} size={16} />)}{reviews != null && <Body style={{ fontSize: 12 }}>({reviews} Reviews)</Body>}</View>; }
